repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
    - id: go-imports
    - id: go-build
    - id: go-mod-tidy

- repo: https://github.com/golangci/golangci-lint
  rev: v1.59.1
  hooks:
    -   id: golangci-lint
